---
- hosts: all
  become: true
  roles:
    - base

- hosts: docker
  become: true
  tags:
    - docker
  roles:
    - docker-host

- hosts: minecraft
  tags:
    - minecraft
  roles:
    - minecraft