---

- name: Add admin user to the docker group
  user: append=yes 
        user={{ lookup('env','USER') }}
        groups=docker

- name: Install packages required for docker repo
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Get docker repo gpg key
  apt_key:  keyserver=hkp://p80.pool.sks-keyservers.net:80
            id=58118E89F3A912897C070ADBF76221572C52609D

- name: Install docker-engine
  apt:  name=docker-engine 
        state=latest
        update_cache=yes

- name: Install requirements for managing docker containers with ansible
  pip: name={{ item }}
  become: true
  with_items:
    - docker-py
    - docker-compose
